### ISSUE TITLE
RadioSerialHandler.h

### ISSUE THREAD

**Issue by albinger** [rhsanborn/AlincoDXSR8CAT#1]
I know it has been years since this was last updated but is there any chance you could sync your updates that include the RadioSerialHandler.h file?

**Comment by rhsanborn** [comment]
I just pushed them up. Try it now. Note: This is pretty green and not super robust. It's on my list to get back to, but some other things have taken precedent. I'll be interested to see how it goes for you. Let me know! If your QRZ page and Git avatar are any indication, your a beer making, IT working ham operator. Good luck from a fellow beer making, IT working ham from Michigan.

- AE8RS
